### ISSUE TITLE
AttributeError: 'X509' object has no attribute 'wrapped' with current simp_le version

### ISSUE THREAD

**Issue by sseemayer** [m3adow/docker-letsencrypt-simp_le#1]
Thanks for your great minimal docker image! I've built the plugin dokku/dokku-letsencrypt around it to auto-retrieve let's encrypt certificates for dokku apps. Since some recent simp_le updates, however, this docker image fails with the following error message:

```
$ docker pull m3adow/letsencrypt-simp_le
$ docker run --rm m3adow/letsencrypt-simp_le --test
.E.EE.....E.E.............F
======================================================================
ERROR: test_save_ignore_unpersisted (__main__.CertFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./simp_le.py", line 625, in test_save_ignore_unpersisted
    self.plugin.save(self.all_data)
  File "./simp_le.py", line 768, in save
    return self.save_to_file(self.dump_cert(data.cert))
  File "./simp_le.py", line 459, in dump_cert
    return OpenSSL.crypto.dump_certificate(self.typ, data.wrapped).strip()
  File "/usr/lib/python2.7/site-packages/acme/jose/util.py", line 44, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'X509' object has no attribute 'wrapped'
[... the same error appearing in several other tests ...]
```

According to kuba/simp_le#70 and kuba/simp_le#73 , this happens when mixing python package versions that are not supported by simp_le. They furthermore recommend to always run simp_le in a virtualenv.

**Comment by sseemayer** [comment]
I've manually done a `apk add --update py-pip py-virtualenv gcc python-dev musl-dev libffi-dev openssl-dev` inside of the container, ran the `./venv.sh` script included in the simp_le repo and was able to complete the unit tests successfully from the virtualenv. One possible way of fixing this would therefore be to install the additional alpine packages required for compiling the required python packages, creating the virtualenv, compiling the packages and then running simp_le from the virtualenv although that would make the docker image significantly bigger.

**Comment by sseemayer** [comment]
As it turns out, simply re-building this image and pushing it back to docker hub should be enough. At least that worked to fix things for me :)

**Comment by m3adow** [comment]
Hi,

thanks for your bug report. If I understand you correctly simply rebuilding the image should be enough to fix that? I just did it. At the moment I have very little spare time and no fully working testing environment, so it'll be some time until I can test it. If you want, you can test the functionality and close the issue, otherwise I'll close it as soon as I was able to test which could take a couple of weeks.

**Comment by sseemayer** [comment]
That fixed things, thanks a lot! :+1:
